### ISSUE TITLE
Question on calculating V_soft_

### ISSUE THREAD

**Issue by Git-123-Hub** [mokeddembillel/Soft-Q-Learning#1]
First of all, Thanks for your work.

I'm a little confused about the way you calculate V_soft_.
It seems that you implement eqution [10] in
https://github.com/mokeddembillel/Soft-Q-Learning/blob/50f0a3fa1914f28649ad6973fa4366da34ad8170/SQL_torch.py#L122

I've also noticed that you use multiple samples to calculate this value,
but I can't find code about Importance sampling(as the denominator in eq[10]).

Also, I don't really understand the meaning of `action_dim * log(2)` in 
https://github.com/mokeddembillel/Soft-Q-Learning/blob/50f0a3fa1914f28649ad6973fa4366da34ad8170/SQL_torch.py#L123

**Comment by mokeddembillel** [comment]
Hi, you're welcome

1- At first, I remember that I implemented it the same way as they did in the article. but I don't really remember why I removed the importance sampling term. maybe because it didn't work for me. and by the way, this is the same way they implemented it in their TensorFlow version.

2- log(2) is just a regularization term.

**Comment by Git-123-Hub** [comment]
Thanks a lot.
